<?php
/**
 * @file
 * Code for the Stanford SimpleSAML PHP module.
 */

/**
 * Implements hook_block_info().
 */

function stanford_ssp_block_info() {
  $blocks['stanford_ssp_login_block'] = array(
    'info'       => t('Stanford SimpleSAML PHP Authentication'),
    'status'     => 1,
    'visibility' => BLOCK_VISIBILITY_NOTLISTED,
    'pages'      => "user\nuser/*",
    'weight'     => 0,
    'region'     => '',
    'cache'      => DRUPAL_NO_CACHE,
  );
  return $blocks;
}


/**
 * Implements hook_block_configure().
 */

function stanford_ssp_block_configure($delta = '') {
  $form = array();
  switch ($delta) {
    case 'stanford_ssp_login_block':
      $form['stanford_ssp_link_text'] = array(
      '#type'          => 'textfield',
      '#title'         => t('Text of the SimpleSAML PHP login link'),
      '#require'       => TRUE,
      '#size'          => 60,
      '#description'   => t('Here you can replace the text of the SimpleSAML PHP link.'),
      '#default_value' => variable_get('stanford_ssp_link_text', 'SUNetID Login'),
    );
  }
  return $form;
}

/**
 * Implements hook_block_view().
 */

function stanford_ssp_block_view($delta = '') {
  $block = array();
  switch ($delta) {
    case 'stanford_ssp_login_block':
      // only show block for anonymous users
      if (user_is_logged_in()) {
        return $block;
      }
      $stanford_ssp_link_text = variable_get('stanford_ssp_link_text', 'SUNetID Login');
      $block = array(
        'subject' => t('SUNetID Login'),
        'content' => l($stanford_ssp_link_text, 'saml_login'),
      );
      break;
  }
  return $block;
}

/**
 * Implements hook_menu().
 */

function stanford_ssp_menu() {
  $items = array();

  $items['stanford_ssp/403'] = array(
    'page callback' => 'stanford_ssp_error_page',
    'access callback' => 'stanford_ssp_access_check',
    'type' => MENU_CALLBACK,
  );
  $items['admin/config/people/simplesamlphp_auth/config'] = array(
    'type' => MENU_DEFAULT_LOCAL_TASK,
    'title' => 'SimpleSAML PHP Configuration',
    'weight' => -1,
  );
  $items['admin/config/people/simplesamlphp_auth/mappings'] = array(
    'page callback' => 'drupal_get_form',
    'page arguments' => array('stanford_ssp_mapping_form'),
    'access arguments' =>  array('administer users'),
    'type' => MENU_LOCAL_TASK,
    'title' => 'Role Mappings',
    'weight' => 0,
  );

  return $items;
}

/**
 * Handle 403 errors by redirecting users to saml_login for login.
 *
 * If, however, they are already logged in and don't have access
 * (for instance, a normal user requesting /admin), then display
 * a normal error message.
 */

function stanford_ssp_error_page() {
  // Figure out where the user is trying to go before redirecting him.
  $dest = drupal_get_destination();
  // We have to unset $_GET['destination'] here, otherwise drupal_goto() will ignore the $path argument.
  // See https://api.drupal.org/api/drupal/includes!common.inc/function/drupal_goto/7.
  unset($_GET['destination']);
  // Redirect the user to saml_login, then send him on his way.
  drupal_goto('saml_login', array('query' => $dest));
}

/**
 * @return bool TRUE if the user is anonymous, FALSE if they are not.
 */
function stanford_ssp_access_check() {
  if (user_is_anonymous()) {
    return TRUE;
  }
  else {
    return FALSE;
  }
}

/**
 *
 * Implements hook_form().
 *
 * Configuration form for the SimpleSAML PHP role mapping.
 *
 * @param $form
 * @param $form_state
 */
function stanford_ssp_mapping_form($form, &$form_state) {
  $roles = user_roles(TRUE);
  $roles = array_combine($roles, $roles);
  $form['mappings'] = array(
    '#type' => 'fieldset',
    '#title' => t('Role Mappings'),
    '#description' => t('Map a SimpleSAML PHP entitlement to a Drupal role.'),
  );
  $form['mappings']['entitlement'] = array(
    '#type' => 'textfield',
    '#title' => t('Entitlement'),
    '#required' => TRUE,
  );
  $form['mappings']['role'] = array(
    '#type' => 'select',
    '#title' => t('Drupal Role'),
    '#required' => TRUE,
    '#options' => $roles,
  );
  $form['submit'] = array(
    '#type' => 'submit',
    '#value' => t('Add Role Mapping'),
  );
  return $form;
}

/**
 *
 * Implements hook_form_submit().
 *
 * @param $form
 * @param $form_state
 */
function stanford_ssp_mapping_form_submit($form, &$form_state) {
  $entitlement = $form_state['values']['entitlement'];
  $role = $form_state['values']['role'];
  stanford_ssp_map_entitlement_to_role($entitlement, $role);
}
/**
 * @param string $entitlement A value in eduPersonEntitlement, e.g., anchorage_support
 * @param string $role The name of the role
 *
 * Map an entitlement to a role.
 */
function stanford_ssp_map_entitlement_to_role($entitlement, $role) {
  $entitlement = check_plain($entitlement);
  // look up rid
  $role_object = user_role_load_by_name($role);
  if (!$role_object) {
    drupal_set_message(t('No role exists with the name "@role"', array('@role' => $role)), 'error');
  }
  else {
    $rid = $role_object->rid;
    // look up current role mapping, if any
    $role_mapping = variable_get('simplesamlphp_auth_rolepopulation');
    if (!empty($role_mapping)) {
      $role_mapping .= "|";
    }
    // Add our mapping
    $role_mapping .= $rid . ":eduPersonEntitlement,=," . $entitlement;
    // Save our mapping
    variable_set('simplesamlphp_auth_rolepopulation', $role_mapping);
    $message = t('Mapped the "@entitlement" entitlement to the "@role" role.', array('@entitlement' => $entitlement, '@role' => $role));
    drupal_set_message($message);
    watchdog('stanford_ssp', $message);
  }
}

/**
 * Implements hook_theme_registry_alter().
 */
function stanford_ssp_theme_registry_alter(&$theme_registry) {
  $theme_registry['webform_view_messages']['function'] = 'stanford_ssp_webform_login';
}

/**
 * Overrides theme_webform_view_messages().
 * Send user to saml_login instead of user/login if he doesn't have access to the form.
 */
function stanford_ssp_webform_login($variables) {
  global $user;

  $node = $variables['node'];
  $page = $variables['page'];
  $submission_count = $variables['submission_count'];
  $user_limit_exceeded = $variables['user_limit_exceeded'];
  $total_limit_exceeded = $variables['total_limit_exceeded'];
  $allowed_roles = $variables['allowed_roles'];
  $closed = $variables['closed'];
  $cached = $variables['cached'];

  $type = 'warning';

  if ($closed) {
    $message = t('Submissions for this form are closed.');
  }
  elseif ($node->webform['confidential'] && user_is_logged_in()) {
    $message = t('This form is confidential. You much <a href="!url">Log out</a> to submit it.',
      array('!url' => url('/user/logout', array('query' => array('destination' => request_uri())))));
  }
  // If open and not allowed to submit the form, give an explanation.
  elseif (array_search(TRUE, $allowed_roles) === FALSE && $user->uid != 1) {
    if (empty($allowed_roles)) {
      // No roles are allowed to submit the form.
      $message = t('Submissions for this form are closed.');
    }
    elseif ($user->uid == 0) {
      // The user is anonymous, so (at least) needs to log in to view the form.
      $login = url('saml_login', array('query' => drupal_get_destination()));
      $register = url('user/register', array('query' => drupal_get_destination()));
      if (variable_get('user_register', 1) == 0) {
        $message = t('You must <a href="!login">log in with your SUNetID</a> to view this form.', array('!login' => $login));
      }
      else {
        $message = t('You must <a href="!login">log in with your SUNetID</a> or <a href="!register">register</a> to view this form.', array('!login' => $login, '!register' => $register));
      }
    }
    else {
      // The user must be some other role to submit.
      $message = t('You do not have permission to view this form.');
      $type = 'error';
    }
  }

  // If the user has exceeded the limit of submissions, explain the limit.
  elseif ($user_limit_exceeded && !$cached) {
    if ($node->webform['submit_interval'] == -1 && $node->webform['submit_limit'] > 1) {
      $message = t('You have submitted this form the maximum number of times (@count).', array('@count' => $node->webform['submit_limit']));
    }
    elseif ($node->webform['submit_interval'] == -1 && $node->webform['submit_limit'] == 1) {
      $message = t('You have already submitted this form.');
    }
    else {
      $message = t('You may not submit another entry at this time.');
    }
  }
  elseif ($total_limit_exceeded && !$cached) {
    if ($node->webform['total_submit_interval'] == -1 && $node->webform['total_submit_limit'] > 1) {
      $message = t('This form has received the maximum number of entries.');
    }
    else {
      $message = t('You may not submit another entry at this time.');
    }
  }

  // If the user has submitted before, give them a link to their submissions.
  if ($submission_count > 0 && $node->webform['submit_notice'] == 1 && !$cached) {
    if (empty($message)) {
      $message = t('You have already submitted this form.');
      $type = 'status';
    }
    $message .= ' ' . t('<a href="!url">View your previous submissions</a>.', array('!url' => url('node/' . $node->nid . '/submissions')));
  }

  if ($page && isset($message)) {
    drupal_set_message($message, $type, FALSE);
  }
}