<?php
/**
 * @file
 * Code for the Stanford Jumpstart Login feature.
 */

include_once 'stanford_saml_block.features.inc';

/**
 * Implements hook_block_info().
 */

function stanford_saml_block_info() {
  $blocks['stanford_ssp_login_block'] = array(
    'info'       => t('Stanford SimpleSAML PHP Authentication'),
    'status'     => 1,
    'visibility' => BLOCK_VISIBILITY_NOTLISTED,
    'pages'      => "user\nuser/*",
    'weight'     => 0,
    'region'     => '',
    'cache'      => DRUPAL_NO_CACHE,
  );
  return $blocks;
}


/**
 * Implements hook_block_configure().
 */

function stanford_saml_block_configure($delta = '') {
  $form = array();
  switch ($delta) {
    case 'stanford_ssp_login_block':
      $form['stanford_ssp_link_text'] = array(
      '#type'          => 'textfield',
      '#title'         => t('Text of the SimpleSAML PHP login link'),
      '#require'       => TRUE,
      '#size'          => 60,
      '#description'   => t('Here you can replace the text of the SimpleSAML PHP link.'),
      '#default_value' => variable_get('stanford_ssp_link_text', 'SUNetID Login'),
    );
  }
  return $form;
}

/**
 * Implements hook_block_view().
 */

function stanford_saml_block_view($delta = '') {
  $block = array();
  switch ($delta) {
    case 'stanford_ssp_login_block':
      // only show block for anonymous users
      if (user_is_logged_in()) {
        return $block;
      }
      $stanford_ssp_link_text = variable_get('stanford_ssp_link_text', 'SUNetID Login');
      $block = array(
        'subject' => t('SUNetID Login'),
        'content' => l($stanford_ssp_link_text, 'saml_login'),
      );
      break;
  }
  return $block;
}


/**
 * Implements hook_form_FORMID_alter().
 *
 * @param  [type] &$form       [description]
 * @param  [type] &$form_state [description]
 * @return [type]              [description]
 */
function stanford_saml_block_form_user_login_alter(&$form, &$form_state) {

  $form['saml_auth'] = array(
    '#type' => 'fieldset',
    '#title' => "SUNet Login",
    '#weight' => -10,
  );

  $form['saml_auth']['saml_link'] = array(
    '#prefix' => "<p>",
    '#markup' => l(t("Log in with your SUNet ID »"), "saml_login"),
    '#suffix' => "</p>",
  );

  $form['drupal_auth'] = array(
    '#type' => 'fieldset',
    '#title' => "Drupal Login",
    '#weight' => 0,
  );

  // Remove the Federated login link.
  if (isset($form["links"])) {
    unset($form["links"]);
  }

}
